name: CI Maven

on:
  push:
    branches: [ master ]  # Remplace "main" si ta branche par défaut a un autre nom
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/java-setup
      - name: test
        run: ls
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/java-setup

      - name: Run unit tests
        run: mvn test

  mutation-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    if: github.ref == 'refs/heads/master' || github.event_name == 'pull_request'
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/java-setup

      - name: Run PIT Mutation Testing
        run: mvn org.pitest:pitest-maven:mutationCoverage

      - name: Upload mutation test report
        uses: actions/upload-artifact@v4
        with:
          name: pitest-report
          path: target/pit-reports

  
