name: CI Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/java-setup
      
      - name: Build with Maven
        run: mvn -B package
        working-directory: java

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/java-setup

      - name: Run unit tests
        run: mvn test
        working-directory: java

  mutation-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    if: github.ref == 'refs/heads/master' || github.event_name == 'pull_request'
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/java-setup

      - name: Run PIT Mutation Testing
        run: mvn org.pitest:pitest-maven:mutationCoverage -X
        working-directory: java

      - name: Upload mutation test report
        uses: actions/upload-artifact@v4
        with:
          name: pitest-report
          path: java/target/pit-reports

  libyear:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/java-setup

      - name: Run libyear for dependencies
        run: mvn io.github.mfoo:libyear-maven-plugin:analyze
        working-directory: java
